# Generated by Django 4.2 on 2024-10-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagen', models.CharField(max_length=500)),
                ('tamanno', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('moneda', models.CharField(max_length=10)),
            ],
        ),
    ]
