# Generated by Django 4.2 on 2024-07-31 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_wsp', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('enlace_temu', models.CharField(max_length=300)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio', models.IntegerField(default=0)),
                ('encargado', models.BooleanField(default=False)),
                ('recibido', models.BooleanField(default=False)),
                ('entregado', models.BooleanField(default=False)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.cliente', to_field='numero_wsp')),
                ('tipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facturacion.tipopago', to_field='tipo')),
            ],
        ),
    ]
