# Generated by Django 4.2 on 2024-08-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_cliente_nombre_producto_peso_alter_producto_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
