# Generated by Django 4.2 on 2024-08-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_alter_producto_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cambio_cup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='cambio_mlc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='nota',
            field=models.TextField(default=''),
        ),
    ]
